version: "3.6"
services:
  php:
    image: charlesportwoodii/php:7.2
    working_dir: /var/www
    ports:
      - "8080:8080"
    volumes:
      - ${PWD-.}:/var/www
    entrypoint: bash -lc "/var/www/rr serve -d -v -c ./rr.yaml"
    networks:
      main:
        aliases:
          - php

networks:
  main: